Repository woowacourse-teams/2022-teatime, pull requests merged in 2022-08, with the labels that each got.

#145 [FE] dateTime 변환 방식 변경
  front/src/components/CoachTimeList/index.tsx
  front/src/components/TimeList/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#142 [FE] favicon및 로고 변경
  front/public/favicon.ico
  front/public/index.html
  front/src/assets/logo.png
  front/src/assets/logo.svg
  front/src/components/Header/index.tsx
  front/webpack.config.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#141 [FE] 예약 승인 기능 구현
  front/src/components/Board/index.tsx
  front/src/components/Board/styles.ts
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/components/Calendar/index.tsx
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/Coach/styles.ts
  front/src/styles/theme.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#144 [BE] 달의 마지막 날에 테스트가 깨지는 문제 수정
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🐞수정

#149 [FE] 캘린더 컴포넌트 리팩토링
  front/src/components/Calendar/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#154 [BE] cors 에러 처리
  back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
Labels: 🐶백엔드, 🐞수정

#156 [BE] 백엔드 테스트 자동화 적용
  .github/workflows/backend-build-test.yml
Labels: 🐶백엔드, 🌟기능

#157 [BE] 백엔드 테스트 자동화 적용
  .github/workflows/backend-build-test.yml
Labels: 🐶백엔드, 🌟기능

#159 [BE] github action 서브모듈 토큰 에러 수정
  .github/workflows/backend-build-test.yml
Labels: 🐶백엔드, 🐞수정

#161 [FE] 면담 예약 정보와 작성한 내용을 서버와 통신하는 기능
  front/src/components/Textarea/index.tsx
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/InterviewForm/index.tsx
  front/src/pages/InterviewForm/styles.ts
  front/src/styles/theme.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#162 [BE] github action 토큰 에러 수정 및 Caching 추가
  .github/workflows/backend-build-test.yml
Labels: 🐶백엔드, 🌟기능, 🐞수정

#167 [FE] 면담 정보 페이지 리팩토링
  front/src/App.tsx
  front/src/components/SheetInfo/index.tsx
  front/src/components/SheetInfo/styles.ts
  front/src/mocks/data.ts
  front/src/pages/AddSheet/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#165 [BE] 코치가 진행 중인 면담을 취소하는 기능
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치

#171 [FE] 빌드 스크립트 수정
  front/package.json
Labels: 🐱프론트엔드, 🐞수정

#160 [BE] 코치의 크루 면담 현황 목록을 불러오는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/CoachReservationsRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/CrewSaveRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachMainReservationDto.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachReservationsResponse.java
  back/src/main/java/com/woowacourse/teatime/domain/Crew.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/CrewService.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍🏫코치

#173 [FE] import 정렬
  front/src/components/BoardItem/index.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Loading/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/SheetInfo/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/context/ScheduleProvider.tsx
  front/src/hooks/useFetch.ts
  front/src/index.tsx
  front/src/mocks/browser.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/SelectUser/index.tsx
  front/src/utils/index.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#172 [BE] 확정된 면담을 진행중인 면담 상태로 바꾸는 기능 구현
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachMainReservationDto.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능

#175 [BE] 진행 중인 면담을 완료하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/exception/UnableToDoneReservationException.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍🏫코치

#153 [BE] 배포 환경에서 디버깅을 할 수 있도록 로깅 처리를 한다
  back/.gitignore
  back/src/main/java/com/woowacourse/teatime/aspect/LogAspect.java
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/resources/logback-spring.xml
Labels: 🐶백엔드, 🌟기능

#178 [FE] 캘린더 월 변경 버그 수정
  front/src/components/Calendar/index.tsx
  front/src/components/Calendar/styles.ts
  front/src/components/CoachTimeList/index.tsx
  front/src/components/CoachTimeList/styles.ts
  front/src/components/DateBox/styles.ts
  front/src/components/TimeList/index.tsx
  front/src/components/TimeList/styles.ts
  front/src/hooks/useTimeList.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#128 [BE] 코치가 크루의 면담 히스토리를 조회하는 기능구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachFindCrewHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍🏫코치

#179 [BE] 크루가 자신의 히스토리를 조회할 때 면담 상태를 함께 반환하도록 수정
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/domain/Sheet.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🌈리팩터링

#180 [FE] 빌드 스크립트 수정
  front/package.json
Labels: 🐱프론트엔드, 🐞수정

#184 [BE] 크루가 자신의 면담 시트를 조회하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/SheetDto.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/SheetFindResponse.java
  back/src/main/java/com/woowacourse/teatime/repository/SheetRepository.java
  back/src/main/java/com/woowacourse/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/repository/SheetRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루

#188 [FE] 예약한 크루 목록 조회 api 연동
  front/src/App.tsx
  front/src/components/BoardItem/styles.ts
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/SelectUser/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#189 [BE] 테스트 코드 리팩터링
  back/src/main/java/com/woowacourse/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
Labels: 🐶백엔드, 🌈리팩터링

#191 [BE] 코치가 크루의 면담 시트를 조회하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachFindCrewSheetResponse.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnSheetResponse.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/domain/SheetStatus.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍🏫코치

#194 [FE] 404 페이지 구현
  front/src/App.tsx
  front/src/assets/not-found.png
  front/src/pages/NotFound/index.tsx
  front/src/pages/NotFound/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#192 [FE] 코치 예약 취소기능 구현
  front/src/components/BoardItem/index.tsx
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#196 [BE] 면담취소 시 아이디, Role을 헤더에 담도록 수정
  back/src/main/java/com/woowacourse/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌈리팩터링

#199 [BE] 스케줄 수정 및 삭제할 때, 그 스케줄에 예약이 되어 있으면 SqlException 발생 문제 해결
  back/src/main/java/com/woowacourse/teatime/exception/UnableToUpdateSchedule.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ScheduleControllerTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🪃트러블슈팅, 🐞수정

#204 [FE] 코치가 면담 시트를 보는 페이지 UI 구현
  front/src/App.tsx
  front/src/components/SheetInfo/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/constants/index.ts
  front/src/pages/ViewSheet/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#202 [FE] 재예약이 가능한 문제 수정
  front/src/components/CoachTimeList/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/context/ScheduleProvider.tsx
  front/src/pages/NotFound/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#203 [BE] 크루가 자신의 면담 시트를 수정하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/SheetAnswerUpdateDto.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/SheetAnswerUpdateRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnSheetResponse.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/domain/Sheet.java
  back/src/main/java/com/woowacourse/teatime/exception/UnModifiableSheetException.java
  back/src/main/java/com/woowacourse/teatime/exception/UnableToSubmitSheetException.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/SheetService.java
  back/src/main/resources/static/docs/api.html
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/domain/SheetTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루

#206 [FE] 일정 승인시 정렬기능 추가
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#210 [BE] 면담 시트 답변에 빈칸이 포함된 상태로 제출할 경우 예외를 반환하도록 수정
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/ScheduleController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/SheetAnswerUpdateDto.java
  back/src/main/java/com/woowacourse/teatime/exception/CannotSubmitBlankException.java
  back/src/main/java/com/woowacourse/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🌈리팩터링

#208 [FE] 예약 거절 기능 추가
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#211 [BE] 해당 일에 예약이 하나라도 있으면 스케쥴 업데이트가 안되는 문제 수정
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🪃트러블슈팅

#215 [FE] 일정 드래그 기능 추가
  front/src/components/Board/index.tsx
  front/src/components/BoardItem/index.tsx
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#220 면담 시트 작성 페이지 api 연동 수정
  front/src/App.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/SheetInfo/index.tsx
  front/src/components/SheetInfo/styles.ts
  front/src/components/Textarea/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/constants/index.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/SelectUser/index.tsx
  front/src/pages/ViewSheet/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#221 [FE] 드래그 기능 수정
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#224 [FE] 일정 추가 버튼 수정
  front/src/assets/schedule-white.svg
  front/src/components/SheetInfo/index.tsx
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#225 [BE] Tomcat시간을 KST 설정
  back/src/main/java/com/woowacourse/teatime/TeatimeApplication.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
Labels: 🐶백엔드, 🐞수정

#229 [FE] 코치 메인페이지 리팩토링
  front/src/components/BoardItem/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#231 [FE] 캘린더 시간 스크롤 개선
  front/src/components/CoachTimeList/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#233 [FE] 드래그 스타일 개선
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/pages/Coach/index.tsx
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#236 [BE] 깃허브 웹훅 테스트
  back/.gitignore
Labels: 🚀배포

#237 면담 시트 컴포넌트 리팩토링
  front/src/components/SheetInfo/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#244 [BE] 크루가 자신의 면담 히스토리를 조회할때 crewId를 헤더로 받도록 수정
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🐞수정

#243 [FE] 지난 날짜는 예약 불가능하도록 수정
  front/src/components/Calendar/index.tsx
  front/src/components/Calendar/styles.ts
  front/src/components/DateBox/index.tsx
  front/src/components/DateBox/styles.ts
  front/src/context/ScheduleProvider.tsx
  front/src/utils/index.ts
Labels: 🐱프론트엔드, 🐞수정

#240 [FE] 보드 컴포넌트 드래그 스타일 추가
  front/src/components/Board/index.tsx
  front/src/components/Board/styles.ts
  front/src/components/BoardItem/index.tsx
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#248 [FE] dayjs 제거 및 날짜 /시간 변환 구현
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/BoardItem/index.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/SheetInfo/index.tsx
  front/src/components/SheetInfo/styles.ts
  front/src/components/TimeList/index.tsx
  front/src/constants/index.ts
  front/src/pages/Coach/index.tsx
  front/src/typings/domain.ts
  front/src/utils/index.ts
Labels: 🐱프론트엔드, 🐞수정

#249 크루 히스토리 페이지 UI 구현
  front/src/App.tsx
  front/src/components/SheetInfo/styles.ts
  front/src/components/TableRow/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/constants/index.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
  front/src/styles/theme.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#251 [FE] 크루 히스토리 면담 내용보기 및 면담 삭제 기능
  front/src/assets/trash.svg
  front/src/components/TableRow/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#253 [FE] 누락된 색상 변경
  front/src/components/BoardItem/styles.ts
  front/src/pages/NotFound/styles.ts
Labels: 🐞수정

#258 [FE] 면담 시트 컴포넌트 리팩토링
  front/src/App.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/ReservationInfo/styles.ts
  front/src/components/SheetInfo/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/constants/index.ts
  front/src/pages/AddSheet/index.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/Sheet/index.tsx
  front/src/pages/Sheet/styles.ts
  front/src/pages/ViewSheet/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#260 [BE] 로깅 전략 고도화
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/resources/console-appender.xml
  back/src/main/resources/dev-warn-appender.xml
  back/src/main/resources/file-error-appender.xml
  back/src/main/resources/file-info-appender.xml
  back/src/main/resources/logback-spring.xml
  back/src/main/resources/prod-warn-appender.xml
Labels: 🐶백엔드, 🌟기능

#264 [FE] 스낵바 기능 구현
  front/public/index.html
  front/src/App.tsx
  front/src/ModalPortal.tsx
  front/src/Portal.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/Snackbar/index.tsx
  front/src/components/Snackbar/styles.ts
  front/src/context/SnackbarProvider.tsx
  front/src/hooks/useSnackbar.ts
  front/src/pages/Coach/index.tsx
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#267 크루 면담 시트 수정 시 Resquest에 questionContent 추가
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/SheetAnswerUpdateDto.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🌈리팩터링, 🐞수정

#271 [FE] Authorization code 받아오는 기능
  front/src/App.tsx
  front/src/constants/index.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/pages/SelectUser/index.tsx
  front/src/pages/SelectUser/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#273 SonarQube를 적용
  .github/workflows/build.yml
  back/build.gradle
Labels: 🐶백엔드, 🌟기능

#272 [FE] 코치가 보는 크루 히스토리 페이지 구현
  front/src/App.tsx
  front/src/components/BackButton/index.tsx
  front/src/components/BackButton/styles.ts
  front/src/components/HistoryItem/index.tsx
  front/src/components/HistoryItem/styles.ts
  front/src/components/ReservationInfo/index.tsx
  front/src/components/ReservationInfo/styles.ts
  front/src/components/Sheet/index.tsx
  front/src/components/Sheet/styles.ts
  front/src/components/Textarea/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/constants/index.ts
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Sheet/index.tsx
  front/src/styles/common.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능, 🧑‍🏫코치

#275 [FE] 번들 사이즈 분석 및 개선
  front/package-lock.json
  front/package.json
  front/webpack.config.ts
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#277 [FE] 로그인 api 연결
  front/src/pages/Certification/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#284 [BE] 특정 인물만 슬랙 로그인에 실패하는 에러 수정
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🧑‍🏫코치, 🐞수정

#283 [FE] bundle analyzer 설정 수정
  front/webpack.config.ts
Labels: 🐱프론트엔드, 🐞수정

#291 [FE] 로그인 api 연동하기
  front/src/components/Calendar/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/constants/index.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/utils/localStorage.ts
Labels: 🐱프론트엔드, 🌟기능

#292 [FE] api 오타 수정
  front/src/pages/Crew/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#293 [FE] 로그인 path 수정
  front/src/pages/Certification/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#290 [BE] 로그인이 포함 된 컨트롤러를 구현한다.
  back/src/main/java/com/woowacourse/teatime/auth/controller/dto/LoginResponse.java
  back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
  back/src/main/java/com/woowacourse/teatime/exception/UnAuthorizedException.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachControllerV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewControllerV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationControllerV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/ScheduleControllerV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationApproveRequestV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationCancelRequest.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationReserveRequestV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치

#297 [FE] 유틸 파일 분리
  front/src/components/BoardItem/index.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/HistoryItem/index.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/context/ScheduleProvider.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/utils/date.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#299 [BE] admin 계정도 코치로 판별하도록 수정
  back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🐞수정

#303 [FE] 히스토리 시트 이동 핸들러 연결
  front/src/App.tsx
  front/src/components/BoardItem/index.tsx
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#308 [FE] 스케쥴 페이지 route 수정
  front/src/App.tsx
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#307 [BE] UserArgumentResolver를 만들고 면담 취소 api에 적용
  back/src/main/java/com/woowacourse/teatime/auth/support/UserArgumentResolver.java
  back/src/main/java/com/woowacourse/teatime/auth/support/UserAuthenticationPrincipal.java
  back/src/main/java/com/woowacourse/teatime/auth/support/dto/UserRoleDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationControllerV2.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치

#313 [FE] 크루 메인페이지 스타일 수정
  front/src/components/Card/styles.ts
  front/src/pages/Crew/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#310 [FE] 헤더 프로필 이미지 추가
  front/src/components/Header/index.tsx
  front/src/components/Header/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#316 [FE] 로그인된 유저에따른 홈링크 변경
  front/src/App.tsx
  front/src/assets/slack.svg
  front/src/components/Header/index.tsx
  front/src/context/SnackbarProvider.tsx
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🐞수정

#314 [BE] 코치 생성 시 시트 질문들을 생성하도록 수정
  back/src/main/java/com/woowacourse/teatime/auth/infrastructure/PayloadExtractor.java
  back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
  back/src/main/java/com/woowacourse/teatime/auth/support/LoginInterceptor.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetQuestionUpdateDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Question.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java
  back/src/main/java/com/woowacourse/teatime/util/AuthorizationExtractor.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🐞수정

#324 [FE] 시트 컴포넌트 피드백 반영
  front/src/components/BackButton/styles.ts
  front/src/components/HistoryItem/index.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/ReservationInfo/styles.ts
  front/src/components/Sheet/index.tsx
  front/src/pages/CrewSheet/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#320 [FE] 권한에 따른 라우팅 개선
  front/src/App.tsx
  front/src/AuthRoute.tsx
  front/src/components/CoachTimeList/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/context/UserProvider.tsx
  front/src/pages/Certification/index.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#321 [FE] 히스토리가 없는 경우 임시예외처리
  front/src/pages/HistorySheet/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#318 [BE] 로그인 도입으로 수정된 api 테스트 보강
  back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationControllerV2.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceV2Test.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceV2Test.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceV2Test.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceV2Test.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java
Labels: 🐶백엔드, 🌟기능

#326 [FE] 단위 테스트 추가
  front/jest.config.ts
  front/package-lock.json
  front/package.json
  front/src/utils/__test__/date.test.ts
  front/tsconfig.json
Labels: 🐱프론트엔드, 🌟기능

#328 [BE] 상태가 approved인 면담 response에 sheet 상태를 포함하도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachApprovedReservationDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationsResponse.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🌈리팩터링

#332 [FE] startDate의 Date 포맷 변경
  front/src/utils/date.ts
Labels: 🐱프론트엔드, 🐞수정

#334 [FE] new Date 포맷 함수 수정
  front/src/utils/date.ts
Labels: 🐱프론트엔드, 🐞수정

#338 [FE] 히스토리 삭제 시 리랜더링 기능
  front/src/App.tsx
  front/src/components/TableRow/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/pages/CrewHistory/index.tsx
Labels: 🐱프론트엔드, 🌟기능, 🧑‍💻 크루, 🌈리팩터링

#339 [FE] 재접속시 role에 따른 라우팅 변경
  front/src/pages/Coach/index.tsx
  front/src/pages/Home/index.tsx
Labels: 🐱프론트엔드, 🌟기능, 🐞수정

#341 [FE] 토큰이 만료됐을때 에러처리
  front/src/context/UserProvider.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/Crew/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#347 [BE] 프로필 이미지 반환 시 사이즈 수정 및 로그 개선
  back/src/main/java/com/woowacourse/teatime/auth/infrastructure/SlackOpenIdAuth.java
Labels: 🐶백엔드, 🌈리팩터링, 🐞수정

#348 [FE] 면담 완료기능 연동
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#349 [FE] dropdown 컴포넌트 추가
  front/src/components/Dropdown/index.tsx
  front/src/components/Dropdown/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/Header/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/HistorySheet/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#344 [FE] 작성중인 시트 음영처리 기능
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/Home/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#350 [FE] 인증페이지에 로딩컴포넌트 추가
  front/src/pages/Certification/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#351 [FE] history status 삭제 기능 수정
  front/src/components/TableRow/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#355 [FE] snackbar 스타일 수정
  front/src/components/Snackbar/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#354 [FE] title 컴포넌트 수정
  front/src/components/Sheet/index.tsx
  front/src/components/Title/index.tsx
  front/src/components/Title/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/styles/common.ts
Labels: 🐱프론트엔드, 🌟기능

#357 [FE] 크루 히스토리 내용 보기 오류 수정
  front/src/components/Board/styles.ts
  front/src/components/Sheet/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#363 [FE] 랜딩 페이지 추가
  front/src/components/BoardItem/styles.ts
  front/src/index.tsx
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/styles/GlobalFonts.ts
  front/src/styles/GlobalStyle.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#359 [FE] 스케쥴 리팩토링
  front/package.json
  front/src/App.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/Header/styles.ts
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/context/ScheduleProvider.tsx
  front/src/context/SnackbarProvider.tsx
  front/src/hooks/useCalendar.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#367 [FE] dropdown 컴포넌트 수정
  front/src/components/Dropdown/index.tsx
  front/src/components/Dropdown/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/Header/styles.ts
  front/src/components/Modal/styles.ts
  front/src/hooks/useOutsideClick.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#368 [FE] 빌드 스크립트 수정
  front/package.json
Labels: 🐱프론트엔드, 🐞수정

#369 [BE] 코치 스케줄 업데이트 시 발생하는 문제 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ScheduleUpdateRequest.java
Labels: 🐶백엔드, 🐞수정

#375 [FE] 반응형 적용
  front/src/components/Calendar/styles.ts
  front/src/components/Card/styles.ts
  front/src/components/DateBox/styles.ts
  front/src/components/Frame/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/Title/styles.ts
  front/src/pages/Crew/styles.ts
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/styles/GlobalStyle.ts
  front/src/styles/common.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#372 [FE] 커스텀 훅 리팩토링
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ScheduleTimeList/index.tsx
  front/src/hooks/useBoolean.ts
  front/src/hooks/useModal.ts
  front/src/hooks/useSnackbar.ts
  front/src/hooks/useTimeList.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/Coach/index.tsx
  front/src/pages/Crew/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#376 [FE] refetch 기능 추가
  front/src/hooks/useWindowFocus.ts
  front/src/pages/Coach/index.tsx
Labels: 🐱프론트엔드, 🌟기능
