Repository woowacourse-teams/2022-teatime, pull requests merged in 2022-07, with the labels that each got.

#26 [BE] 코치 스케줄 수정 구현
  back/src/main/java/com/woowacourse/teatime/NotFoundScheduleException.java
  back/src/main/java/com/woowacourse/teatime/controller/ScheduleController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/ScheduleUpdateRequest.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedules.java
  back/src/main/java/com/woowacourse/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶backend, 🌟feature, 🧑‍🏫mento

#27 [FE] 스케줄 캘린더 구현
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.tsx
  front/src/assets/check-circle.svg
  front/src/assets/close.svg
  front/src/assets/left-arrow.svg
  front/src/assets/logo.png
  front/src/assets/right-arrow.svg
  front/src/components/Calendar/DateBox.tsx
  front/src/components/Calendar/index.tsx
  front/src/components/Calendar/styles.ts
  front/src/components/Card/index.tsx
  front/src/components/Card/styles.ts
  front/src/components/Conditional/index.tsx
  front/src/components/Frame/index.tsx
  front/src/components/Frame/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/Header/styles.ts
  front/src/components/Modal/index.tsx
  front/src/components/Modal/styles.ts
  front/src/components/ModalPotal/index.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/ReservationInfo/styles.ts
  front/src/components/TimeList/index.tsx
  front/src/components/TimeList/styles.ts
  front/src/constants/index.ts
  front/src/context/ScheduleProvider.tsx
  front/src/hooks/useModal.ts
  front/src/hooks/useSchedules.ts
  front/src/index.tsx
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/SelectUser/index.tsx
  front/src/pages/SelectUser/styles.ts
  front/src/styles/GlobalStyle.ts
  front/src/typings/domain.ts
  front/src/typings/image.d.ts
  front/src/utils/index.ts
  front/tsconfig.json
  front/webpack.config.ts
Labels: 🐱frontend, 🧑‍💻 mentee

#25 [BE] 면담 예약 신청 기능 구현
  back/src/main/java/com/woowacourse/teatime/AlreadyReservedException.java
  back/src/main/java/com/woowacourse/teatime/BadRequestException.java
  back/src/main/java/com/woowacourse/teatime/InvalidYearException.java
  back/src/main/java/com/woowacourse/teatime/NotExistedCrewException.java
  back/src/main/java/com/woowacourse/teatime/NotFoundCoachException.java
  back/src/main/java/com/woowacourse/teatime/NotFoundException.java
  back/src/main/java/com/woowacourse/teatime/NotFoundScheduleException.java
  back/src/main/java/com/woowacourse/teatime/UnAuthorizedException.java
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/CrewIdRequest.java
  back/src/main/java/com/woowacourse/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/domain/Crew.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/repository/CrewRepository.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ScheduleControllerTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/CoachServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶backend, 🌟feature, 🧑‍💻 mentee

#49 [BE] 코치 일정 조회 시 오늘 이후의 일정만 가져오도록 수정
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶backend, 🧑‍💻 mentee, 🌈refactor

#55 [BE] CORS 에러 해결
  back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
Labels: 🐶backend, 🌟feature

#56 [BE] 면담 승인 기능 구현
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedules.java
  back/src/main/java/com/woowacourse/teatime/exception/AlreadyApprovedException.java
  back/src/main/java/com/woowacourse/teatime/exception/AlreadyReservedException.java
  back/src/main/java/com/woowacourse/teatime/exception/BadRequestException.java
  back/src/main/java/com/woowacourse/teatime/exception/InvalidYearException.java
  back/src/main/java/com/woowacourse/teatime/exception/NotExistedCrewException.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundCoachException.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundException.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundReservationException.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundScheduleException.java
  back/src/main/java/com/woowacourse/teatime/exception/UnAuthorizedException.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ScheduleTest.java
  back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java
  back/src/test/java/com/woowacourse/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/service/CoachServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶backend, 🌟feature, 🧑‍🏫mento

#62 [BE] CORS 포트번호 3000에서 8080으로 변경
  back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
Labels: 🐶backend, 🌟feature

#63 [BE] 코치 등록 api 생성
  back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
  back/src/main/java/com/woowacourse/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/CoachSaveRequest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
Labels: 🐶backend, 🌟feature, 🧑‍💻 mentee

#66 [BE] 일정 조회 응답 타임 포멧 형식 수정
  back/src/main/java/com/woowacourse/teatime/controller/dto/ScheduleDto.java
Labels: 🐶backend, 🌈refactor

#70 [BE] 코치 스케줄 조회 오류 해결
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/util/DateTest.java
Labels: 🐶backend

#68 [BE] ControllerAdvice로 에러 핸들링 기능 구현
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/java/com/woowacourse/teatime/exception/dto/ErrorResponse.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/domain/ScheduleTest.java
  back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
Labels: 🐶backend, 🌟feature

#71 [BE] EntityManger 를 이용한 인수 테스트 격리
  back/build.gradle
  back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/DatabaseCleaner.java
Labels: 🐶backend, 🌈refactor

#76 [FE] 코치 스케줄 리팩토링
  front/src/components/CoachTimeList/index.tsx
  front/src/components/TimeList/index.tsx
  front/src/components/TimeList/styles.ts
  front/src/hooks/useCoachTimes.ts
  front/src/hooks/useFetch.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/Coach/styles.ts
  front/src/pages/Home/index.tsx
  front/src/pages/SelectUser/styles.ts
Labels: 🐱frontend, 🌈refactor

#82 [BE] 불필요한 일급 컬렉션 schedules 삭제
  back/src/main/java/com/woowacourse/teatime/controller/dto/ScheduleResponse.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedules.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java
Labels: 🐶backend, 🌈refactor

#86 [BE] 코치 스케줄 조회 관련 날짜 오류 수정
  back/src/main/java/com/woowacourse/teatime/util/Date.java
Labels: 🐶backend, 🐞fix

#87 [FE] 로딩 이미지 추가
  front/src/assets/loading.gif
  front/src/components/Loading/index.tsx
  front/src/pages/Home/index.tsx
  front/src/typings/image.d.ts
  front/webpack.config.ts
Labels: 🐱frontend, 🌟feature

#104 [BE] 면담 시트 생성 기능 구현
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/domain/Question.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/domain/Sheet.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundCrewException.java
  back/src/main/java/com/woowacourse/teatime/repository/QuestionRepository.java
  back/src/main/java/com/woowacourse/teatime/repository/SheetRepository.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
Labels: 🐶backend, 🌟feature

#107 [BE] REST Docs 설정 및 API 문서화 기능 구현
  back/build.gradle
  back/src/docs/asciidoc/api.adoc
  back/src/main/resources/static/docs/api.html
  back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
Labels: 🐶backend, 🌟feature

#106 [BE] 코치에 의한 면담 거절 기능
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/domain/Schedule.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶backend, 🌟feature

#115 [FE] 서버 주소 변경
  front/src/api/index.ts
Labels: 🐱frontend, 🐞fix

#122 [FE] 면담 내용 작성 페이지 UI 구현
  front/src/App.tsx
  front/src/ModalPortal.tsx
  front/src/components/Frame/styles.ts
  front/src/components/Modal/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/components/TimeList/index.tsx
  front/src/components/Title/styles.ts
  front/src/constants/index.ts
  front/src/pages/InterviewForm/index.tsx
  front/src/pages/InterviewForm/styles.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#126 [BE] 프론트 cors 에러 처리
  back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
Labels: 🐶백엔드, 🐞수정

#119 [BE] 크루가 자신의 면담 히스토리를 조회하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/controller/ScheduleController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/CoachSaveRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/ReservationApproveRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/ReservationReserveRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/ScheduleFindRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/request/ScheduleUpdateRequest.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachFindResponse.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnReservationResponse.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/ScheduleDto.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/response/ScheduleFindResponse.java
  back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/service/CoachService.java
  back/src/main/java/com/woowacourse/teatime/service/CrewService.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ScheduleTest.java
  back/src/test/java/com/woowacourse/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/repository/CoachRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/service/CoachServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
  back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
  back/src/test/java/study/LocalDateTimeTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루

#131 [FE] 면담 작성 form 유효성 검사
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/pages/InterviewForm/index.tsx
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#134 [FE] 백엔드 주소 변경
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#137 [FE] 코치 메인 페이지 UI 구현
  front/src/App.tsx
  front/src/assets/clock.svg
  front/src/assets/plus.svg
  front/src/assets/schedule.svg
  front/src/components/Board/index.tsx
  front/src/components/Board/styles.ts
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/components/Modal/index.tsx
  front/src/mocks/data.ts
  front/src/mocks/handlers.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/Coach/styles.ts
  front/src/styles/theme.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#118 [BE] 면담 취소 기능
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java
  back/src/main/java/com/woowacourse/teatime/controller/dto/ReservationCancelRequest.java
  back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/domain/Role.java
  back/src/main/java/com/woowacourse/teatime/exception/NotFoundRoleException.java
  back/src/main/java/com/woowacourse/teatime/exception/UnCancellableReservationException.java
  back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
  back/src/main/resources/static/docs/api.html
  back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
  back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/domain/RoleTest.java
  back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치
