Repository woowacourse-teams/2022-teatime, pull requests merged in 2022-09, with the labels that each got.

#382 [FE] dev, prod URL 변경
  front/.gitignore
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🌟기능

#388 [FE] slack redirect url 수정
  front/src/pages/Home/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#390 [BE] CORS url 수정
  back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
Labels: 🐶백엔드, 🐞수정

#392 [BE] build.gradle에 서브모듈 설정 변경
  back/build.gradle
Labels: 🐶백엔드, 🚀배포

#405 [FE] 면담시트 컴포넌트 스타일 수정
  front/package-lock.json
  front/src/components/BackButton/styles.ts
  front/src/components/Frame/styles.ts
  front/src/components/HistoryItem/styles.ts
  front/src/components/ReservationInfo/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/styles/common.ts
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#409 [FE] 면담시트 제출 로직 변경 및 상태에 따라 면담 삭제 수정
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/Sheet/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/pages/CrewSheet/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#411 [FE] textarea 글자 수 제한하는 기능
  front/src/components/Sheet/index.tsx
  front/src/constants/index.ts
Labels: 🐱프론트엔드, 🌟기능

#404 [BE] 스프링 스케줄러 구현
  back/src/main/java/com/woowacourse/teatime/TeatimeApplication.java
  back/src/main/java/com/woowacourse/teatime/teatime/config/SchedulerConfig.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/exception/UnableToInProgressReservationException.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/scheduler/SchedulerService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/scheduler/SchedulerServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능

#415 [BE] 스케줄러 패키지 이름 변경 및 기존 테스트코드 수정
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
  back/src/main/java/com/woowacourse/teatime/teatime/scheduler/SchedulerService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🐞수정

#416 [BE] 면담 취소시 DB에서 삭제하는 대신 취소된 상태로 변경하도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/ReservationStatus.java
  back/src/main/java/com/woowacourse/teatime/teatime/exception/UnableToCancelReservationException.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/domain/ReservationTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌈리팩터링

#420 [FE] 코치 히스토리 페이지 구현
  front/src/App.tsx
  front/src/components/Header/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/constants/index.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/styles/theme.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#418 [BE] 코치가 자신의 면담 히스토리를 조회하는 기능 구현
  back/src/docs/asciidoc/api.adoc
  back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachController.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍🏫코치

#421 [FE] api 오타 수정 및 삭제 버튼 제거
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CrewHistory/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#426 [BE] 면담을 진행중 상태로 바꿀 때 에러가 발생하는 문제 해결 및 리팩터링
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🐞수정

#429 [FE] 시트내용보기 기능 수정
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/pages/Coach/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CoachSheet/styles.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능, 🐞수정

#430 [FE] 전반적인 스타일 수정
  front/src/assets/cancel.svg
  front/src/components/BoardItem/styles.ts
  front/src/components/ReservationInfo/styles.ts
  front/src/components/TableRow/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/components/Textarea/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#432 [FE] 3차 QA 스타일 수정
  front/src/components/BoardItem/styles.ts
  front/src/components/ReservationInfo/styles.ts
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/Title/styles.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachSheet/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#435 [FE] 3차 QA 요구사항 반영
  front/src/App.tsx
  front/src/components/Header/index.tsx
  front/src/components/ReservationInfo/styles.ts
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/Sheet/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/pages/Coach/styles.ts
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachMain/styles.ts
  front/src/pages/CrewHistory/styles.ts
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewMain/styles.ts
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#440 [FE] 코치 시간 선택상태가 유지되는 문제 수정
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ScheduleTimeList/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#444 [FE] 보드컴포넌트 스크롤바 추가
  front/src/components/Board/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/hooks/useBoolean.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#445 [FE] 빈 내용을 표시하는 기능 추가
  front/src/assets/empty.svg
  front/src/components/Board/index.tsx
  front/src/components/EmptyContent/index.tsx
  front/src/components/EmptyContent/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#447 [FE] 누락된 alt 추가 및 수정
  front/src/components/EmptyContent/index.tsx
  front/src/components/HistoryItem/index.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachMain/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#452 [BE] slack로그인에서 userID를 가져오는 기능 구현
  back/src/main/java/com/woowacourse/teatime/auth/infrastructure/SlackOpenIdAuth.java
  back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
  back/src/main/java/com/woowacourse/teatime/auth/service/UserInfoDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CoachSaveRequest.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CrewSaveRequest.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CrewService.java
  back/src/test/java/com/woowacourse/teatime/teatime/domain/CrewTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java
Labels: 🐶백엔드, 🌟기능

#454 [BE] slack id가 제대로 저장되지 않는 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
Labels: 🐶백엔드, 🐞수정

#450 [FE] api 함수 분리 및 default header 설정
  front/src/api/auth.ts
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/api/index.ts
  front/src/api/reservation.ts
  front/src/components/Header/index.tsx
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/TableRow/index.tsx
  front/src/pages/Certification/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#453 [FE] 히스토리 빈 내용 추가
  front/src/components/TableRow/index.tsx
  front/src/components/TableRow/styles.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#463 [FE] 크루 히스토리 조회 에러 수정
  front/src/pages/CrewHistory/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#456 [BE] 슬랙 알람 기능 구현
  back/src/main/java/com/woowacourse/teatime/auth/exception/SlackException.java
  back/src/main/java/com/woowacourse/teatime/auth/exception/SlackLoginException.java
  back/src/main/java/com/woowacourse/teatime/auth/infrastructure/SlackOpenIdAuth.java
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/java/com/woowacourse/teatime/exception/SlackException.java
  back/src/main/java/com/woowacourse/teatime/teatime/exception/SlackAlarmException.java
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Alarm.java
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/SlackAlarm.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmTitle.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/AlarmDto.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/ReservationControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/util/DateTest.java
  back/src/test/java/study/StringSplitTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치

#466 [BE] 크루가 자신의 히스토리 조회할 때 코치이름이 아닌 크루이름을 보내주는 에러 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledSheet.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepository.java
Labels: 🐶백엔드, 🐞수정

#467 [BE] 히스토리를 조회할 때 최신순으로 볼 수 있도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
Labels: 🐶백엔드, 🐞수정

#464 [FE] 변경된 api 수정 및 닉네임 변경 기능 추가
  front/src/App.tsx
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/components/Header/index.tsx
  front/src/components/Header/styles.ts
  front/src/components/Modal/index.tsx
  front/src/components/Modal/styles.ts
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/ScheduleTimeList/styles.ts
  front/src/components/Snackbar/styles.ts
  front/src/components/TableRow/index.tsx
  front/src/context/UserProvider.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/styles/common.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#470 [FE] 슬랙 url 워크스페이스 수정
  front/src/pages/Home/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#474 [FE] 슬랙 url 수정
  front/src/pages/Home/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#472 [FE] timelist 컴포넌트 리팩토링
  front/src/components/Header/styles.ts
  front/src/components/Modal/styles.ts
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ScheduleTimeList/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#475 [FE] 히스토리 시트가 없을 경우 빈 화면 표시
  front/src/pages/HistorySheet/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#478 [BE] 이름이 변경되면 description도 변경되도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/test/java/com/woowacourse/teatime/teatime/domain/CoachTest.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🐞수정

#488 [BE] 유저의 슬랙 아이디가 다르면 업데이트 시켜주도록 변경
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
Labels: 🐶백엔드, 🐞수정

#491 [FE] 코치 일정 등록 수정
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/utils/__test__/date.test.ts
Labels: 🐱프론트엔드, 🐞수정

#495 [FE] 폰트 최적화
  front/src/styles/GlobalFonts.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#494 [FE] QA 수정사항 반영
  front/src/api/auth.ts
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/api/index.ts
  front/src/api/reservation.ts
  front/src/components/Calendar/styles.ts
  front/src/components/Header/styles.ts
  front/src/hooks/useFetch.ts
  front/src/pages/CoachMain/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Reservation/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#490 [BE] SlackAlarmException 적용 및 불필요한 트랜잭션 전파 옵션 제거
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
Labels: 🐶백엔드, 🐞수정

#496 release: v1.0.1 배포
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/java/com/woowacourse/teatime/teatime/config/AsyncConfig.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  front/src/api/auth.ts
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/api/index.ts
  front/src/api/reservation.ts
  front/src/components/Calendar/styles.ts
  front/src/components/Header/styles.ts
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/hooks/useFetch.ts
  front/src/pages/CoachMain/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/styles/GlobalFonts.ts
  front/src/utils/__test__/date.test.ts
Labels: 🐶백엔드, 🐱프론트엔드, 🚀배포

#500 [FE] 데이터 캐싱하는 기능
  front/src/constants/index.ts
  front/src/pages/CrewMain/index.tsx
  front/src/utils/cacheFetch.ts
Labels: 🐱프론트엔드, 🌟기능

#498 [FE] frontend ci 추가
  .github/workflows/frontend-ci.yml
Labels: 🐱프론트엔드, 🌟기능

#503 [FE] workflow env 설정.
  .github/workflows/frontend-ci.yml
Labels: 🐱프론트엔드, 🐞수정

#504 [FE] workflow 수정
  .github/workflows/frontend-ci.yml
Labels: 🐱프론트엔드, 🐞수정

#505 [FE] 면담 시트 작성 시 자동 높이 조절 기능 추가
  front/src/components/Sheet/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/pages/CrewSheet/index.tsx
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#515 [FE] 코드 스플리팅 적용
  front/src/App.tsx
  front/src/components/Loading/index.tsx
  front/webpack.config.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#513 [FE] 랜딩페이지 스타일 수정
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#511 [FE] 코치 페이지 모바일뷰 구현
  front/src/components/BackButton/styles.ts
  front/src/components/Board/index.tsx
  front/src/components/Board/styles.ts
  front/src/components/DateBox/styles.ts
  front/src/components/Frame/styles.ts
  front/src/components/ReservationInfo/styles.ts
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/components/SelectList/index.tsx
  front/src/components/SelectList/styles.ts
  front/src/components/Sheet/styles.ts
  front/src/components/TableRow/styles.ts
  front/src/hooks/useWindowSize.ts
  front/src/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachMain/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/styles/common.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🌟기능

#516 [FE] 전체적인 스타일 수정
  front/src/components/Board/styles.ts
  front/src/components/Card/styles.ts
  front/src/components/Frame/styles.ts
  front/src/components/Header/styles.ts
  front/src/components/Loading/styles.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/Home/styles.ts
  front/src/pages/NotFound/styles.ts
  front/src/styles/GlobalStyle.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🐞수정

#517 release: v1.1.0 배포
  .github/workflows/frontend-ci.yml
  front/src/App.tsx
  front/src/components/BackButton/styles.ts
  front/src/components/Board/index.tsx
  front/src/components/Board/styles.ts
  front/src/components/Card/styles.ts
  front/src/components/DateBox/styles.ts
  front/src/components/Frame/styles.ts
  front/src/components/Header/styles.ts
  front/src/components/Loading/index.tsx
  front/src/components/Loading/styles.ts
  front/src/components/ReservationInfo/styles.ts
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/components/SelectList/index.tsx
  front/src/components/SelectList/styles.ts
  front/src/components/Sheet/index.tsx
  front/src/components/Sheet/styles.ts
  front/src/components/TableRow/styles.ts
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/constants/index.ts
  front/src/hooks/useWindowSize.ts
  front/src/index.tsx
  front/src/pages/Certification/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachMain/styles.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
  front/src/pages/NotFound/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/styles/GlobalStyle.ts
  front/src/styles/common.ts
  front/src/styles/theme.ts
  front/src/utils/cacheFetch.ts
  front/webpack.config.ts
Labels: 🐱프론트엔드, 🚀배포

#519 [FE] 다음달 스케줄 로드시 깜빡거림 이슈 수정
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#507 [BE] 코치 히스토리 조회시 response에 crewId를 포함하도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🌈리팩터링

#509 [BE] 리마인드 알람 시간과 알람에 포함되는 면담 범위 수정
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🧑‍🏫코치, 🌈리팩터링

#521 [FE] 코치 히스토리에서 완료된 면담 시트 보여주는 기능
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#522 release: v1.1.1 배포
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/typings/domain.ts
Labels: 🐶백엔드, 🐱프론트엔드, 🚀배포

#523 [FE] 히스토리 조회 에러 수정
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachHistory/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#524 release: v1.1.2 배포
  front/src/components/TableRow/index.tsx
  front/src/pages/CoachHistory/index.tsx
Labels: 🐱프론트엔드, 🚀배포

#528 [BE] 크루 자신의 면담 시트를 조회하는 응답에 ReservationStatus를 포함하도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnSheetResponse.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🐞수정

#529 [BE] JPA 성능 최적화
  back/src/main/java/com/woowacourse/teatime/teatime/aspect/LoggingInterceptor.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledReservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/QuestionRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/SheetRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/SheetRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🌈리팩터링

#532 [BE] 코치 프로필(이름, 설명) 일괄 수정 기능
  back/src/main/java/com/woowacourse/teatime/teatime/aspect/QueryCountInspector.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CoachUpdateProfileRequest.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/exception/InvalidProfileInfoException.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/domain/CoachTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
Labels: 🐶백엔드, 🌟기능

#534 [BE] response 필드 네이밍 변경
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnCanceledSheetResponse.java
Labels: 🐶백엔드, 🧑‍💻 크루, 🌈리팩터링

#536 [FE] 5차 QA 수정사항 반영
  front/src/components/Sheet/index.tsx
  front/src/components/Sheet/styles.ts
  front/src/components/TableRow/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#548 [FE] 코치 프로필 수정 페이지 구현
  front/src/App.tsx
  front/src/api/coach.ts
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/components/Header/index.tsx
  front/src/constants/index.ts
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachProfile/styles.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#549 [BE] 크루가 코치 스케쥴 조회할 때 오름차순으로 조회되도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/ScheduleFindResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🐞수정

#551 [FE] 코치 프로필 유효성 검사
  front/src/components/Header/index.tsx
  front/src/components/Sheet/index.tsx
  front/src/constants/index.ts
  front/src/pages/CoachProfile/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#553 [BE] 승인된 예약을 진행중인 예약으로 변경하는 스케쥴러 수정
  back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
Labels: 🐶백엔드, 🌈리팩터링

#555 [FE] 코치 스케줄 등록 범위 수정
  front/src/components/DateBox/index.tsx
  front/src/components/DateBox/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#558 모바일뷰 스타일 수정
  front/src/pages/Home/styles.ts
  front/src/styles/GlobalStyle.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🐞수정

#563 [FE] 예약 마감된 날짜 상태 표시
  front/src/components/DateBox/index.tsx
  front/src/components/DateBox/styles.ts
  front/src/components/ReservationTimeList/styles.ts
  front/src/components/ScheduleTimeList/styles.ts
Labels: 🐱프론트엔드, 🌟기능, 🐞수정
