Repository woowacourse-teams/2022-teatime, pull requests merged in 2022-10, with the labels that each got.

#571 [FE] 코치리스트 반응형 수정
  front/src/components/Card/styles.ts
  front/src/pages/CrewMain/styles.ts
  front/src/styles/theme.ts
Labels: 🐱프론트엔드, 🐞수정

#564 [BE] 크루 메인뷰에서 예약 가능한 코치만 따로 표시해주도록 api 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
Labels: 🐶백엔드, 🌟기능

#567 [FE] 코치 리스트에서 스케줄이 있을 경우 카드에 표시하는 기능
  front/src/components/Card/index.tsx
  front/src/components/Card/styles.ts
  front/src/constants/index.ts
  front/src/pages/CrewMain/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#569 [FE] 캘린더 이전 월 이동 관련 버그 수정
  front/src/components/Calendar/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#572 [FE] 면담 예약 페이지에서 해당 코치 이미지 표시하기
  front/src/pages/CrewMain/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Reservation/styles.ts
Labels: 🐱프론트엔드, 🌟기능, 🐞수정

#579 [ALL] release 자동화
  .github/release-config.yml
  .github/workflows/release-drafter.yml
Labels: 🐶백엔드, 🐱프론트엔드, 🌟기능

#586 [FE] 채널톡을 적용한다.
  front/public/index.html
Labels: 🐱프론트엔드, 🌟기능

#590 [FE] 소형 모바일 사이즈 대응
  front/src/components/Calendar/styles.ts
  front/src/components/DateBox/styles.ts
  front/src/components/TableRow/styles.ts
  front/src/pages/CrewHistory/styles.ts
  front/src/pages/CrewMain/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#583 [FE] 도움말 컴포넌트 추가
  front/src/components/Modal/styles.ts
  front/src/components/Snackbar/styles.ts
  front/src/components/Title/index.tsx
  front/src/components/Tooltip/index.tsx
  front/src/components/Tooltip/styles.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#591 [FE] 캘린더 Title 정렬 수정
  front/src/components/Title/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#593 [BE] 여러 날짜의 스케줄을 한번에 업데이트 할 수 있도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/ScheduleController.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/ScheduleControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🧑‍🏫코치, 🌈리팩터링

#581 [BE] 시트 제출 알람 추가
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmTitle.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/CrewServiceTest.java
Labels: 🐶백엔드, 🌟기능, 🧑‍💻 크루, 🧑‍🏫코치

#578 [BE] 크루 메인뷰에서 발생하는 1+N 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/CoachRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/dto/CoachWithPossible.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/CoachRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
Labels: 🐶백엔드, 🐞수정

#594 [BE] 슬랙 알람 티타임 바로가기 링크 수정
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java
Labels: 🐶백엔드, 🌈리팩터링

#595 [FE] 히스토리 필터링 기능 추가
  front/src/components/Filter/index.tsx
  front/src/components/Filter/styles.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewHistory/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#598 [BE] 크루 메인뷰에서 발생하는 1+N 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/CoachRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/dto/CoachWithPossible.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/CoachRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
Labels: 🐶백엔드, 🐞수정

#599 [BE] 코치 메인뷰에서 발생하는 1+N 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
Labels: 🐶백엔드, 🐞수정

#600 [BE] 코치 메인뷰에서 발생하는 1+N 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
Labels: 🐶백엔드, 🐞수정

#601 [FE] 다중선택 임시적으로 비활성화
  front/src/components/ScheduleTimeList/styles.ts
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드

#610 [BE] 코치가 크루 면담시트 조회하는 api 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindCrewSheetResponse.java
Labels: 🐶백엔드, 🐞수정

#611 [FE] 코치가 보는 크루시트 정보 수정
  front/src/api/crew.ts
  front/src/pages/CoachSheet/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#605 [BE] fetch join 적용, n+1 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/jdbc/ScheduleDao.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/jdbc/ScheduleDaoTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/support/RepositoryTest.java
Labels: 🐶백엔드, 🐞수정

#614 [FE] 다중선택 기능 활성화
  front/src/components/CalendarSelectList/styles.ts
  front/src/components/MultipleTimeList/styles.ts
  front/src/components/ScheduleTimeList/styles.ts
  front/src/hooks/useSelectList.ts
  front/src/pages/CoachSheet/styles.ts
  front/src/pages/Schedule/index.tsx
  front/src/pages/Schedule/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#604 [FE] 소형 모바일 스타일 수정
  front/src/components/Card/styles.ts
  front/src/components/Dropdown/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#620 [FE] 면담 완료 flow 개선
  front/src/api/reservation.ts
  front/src/assets/clock.svg
  front/src/assets/person.svg
  front/src/assets/schedule.svg
  front/src/components/Board/styles.ts
  front/src/components/BoardItem/index.tsx
  front/src/components/BoardItem/styles.ts
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CoachSheet/styles.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#619 [FE] 코치 프로필 미리보기 구현
  front/src/components/Card/index.tsx
  front/src/components/Card/styles.ts
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachProfile/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#625 [BE] 시트 지 질문 필수 여부 체크 및 목록 조회/수정
  back/src/docs/asciidoc/index.adoc
  back/src/docs/asciidoc/question.adoc
  back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/QuestionController.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetQuestionUpdateRequest.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/SheetQuestionResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/SheetQuestionsResponse.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledReservation.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Question.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/QuestionRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/repository/jdbc/QuestionDao.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/QuestionAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/QuestionRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🌟기능

#632 [BE] 시트 제출할 때 알람 로직 비동기로 처리
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
Labels: 🐶백엔드, 🌈리팩터링

#628 [BE] 시트 조회시에 필수 여부(isRequired)를 응답 값에 추가한다
  back/src/docs/asciidoc/crew.adoc
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/SheetDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledSheet.java
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Sheet.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🐞수정

#630 [FE] 사전 질문 조회/수정 기능 추가
  front/src/api/question.ts
  front/src/constants/index.ts
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachProfile/styles.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#638 [BE] 일정 다중선택 시 이전에 등록했던 일정이 사라지는 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/main/java/com/woowacourse/teatime/util/Date.java
  back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🐞수정

#640 [FE] 시트 질문 항목의 필수 여부 표시
  front/src/components/Sheet/index.tsx
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#642 [BE] 시트 문항이 선택일 시 빈칸이어도 제출되도록 수정
  back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewController.java
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetAnswerUpdateDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
  back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/controller/CrewControllerTest.java
  back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/SheetServiceTest.java
Labels: 🐶백엔드, 🐞수정

#645 시트 사전 질문 필수여부 색상 변경
  front/src/components/Textarea/index.tsx
  front/src/components/Textarea/styles.ts
  front/src/pages/CoachProfile/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#647 [BE] async 로직에서 프록시를 전달하는 문제 해결
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/AlarmTargetDto.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java
Labels: 🐶백엔드, 🐞수정

#651 [FE] login api v2로 변경
  front/src/api/auth.ts
Labels: 🐱프론트엔드, 🐞수정

#652 [FE] withCredentials 설정
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#653 [FE] axios defaults 설정 변경
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#654 [FE] axios default 설정 변경
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#655 [BE] exposedHeaders 설정 변경
  back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
Labels: 🐶백엔드, 🐞수정

#656 [FE] login api v2 제거
  front/src/api/auth.ts
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#657 [FE] login api v2로 변경
  front/src/api/auth.ts
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#659 [BE] 빈 스케줄을 등록해도 기존 스케줄이 삭제되지 않는 에러 해결
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🐞수정

#661 [BE] EmbeddedRedis를 arm에서 사용할 수 있도록 구현
  back/src/test/java/com/woowacourse/teatime/auth/support/TestRedisConfig.java
  back/src/test/resources/binary/redis/redis-server-6.2.5-mac-arm64
Labels: 🐶백엔드, 🐞수정

#664 [FE] 리프레시 토큰 api 연동
  front/src/api/auth.ts
  front/src/api/index.ts
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#665 [BE] 토큰 생성 로직 변경
  back/src/main/java/com/woowacourse/teatime/auth/controller/AuthController.java
  back/src/main/java/com/woowacourse/teatime/auth/domain/UserAuthInfo.java
  back/src/main/java/com/woowacourse/teatime/auth/service/LoginService.java
  back/src/main/java/com/woowacourse/teatime/auth/service/UserAuthService.java
Labels: 🐶백엔드, 🐞수정

#666 [BE] Poke 도메인에 JPA Auditing 설정 어노테이션 추가
  back/src/main/java/com/woowacourse/teatime/teatime/domain/Poke.java
Labels: 🐶백엔드, 🐞수정

#669 [BE] CORS 설정 변경 및 인증 관련 테스트 추가
  back/build.gradle
  back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
  back/src/test/java/com/woowacourse/teatime/auth/acceptance/AuthAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/auth/repository/UserAuthInfoRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/auth/service/UserAuthServiceTest.java
  back/src/test/java/com/woowacourse/teatime/auth/support/EmbeddedRedisConfig.java
  back/src/test/resources/binary/redis/redis-server-6.2.5-mac-arm64
Labels: 🐶백엔드, 🌟기능, 🐞수정

#670 [BE] EmbeddedRedisConfig 설정 변경
  back/src/test/java/com/woowacourse/teatime/auth/support/EmbeddedRedisConfig.java
  back/src/test/resources/binary/redis/redis-server-6.2.5-mac-arm64
Labels: 🐶백엔드, 🐞수정

#672 [BE] 코치 프로필 조회시 isPokable 추가
  back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachProfileResponse.java
Labels: 🐶백엔드, 🐞수정

#676 [FE] 토큰 에러 예외사항 추가
  front/src/api/index.ts
  front/src/constants/index.ts
Labels: 🐱프론트엔드, 🐞수정

#673 [BE] Embedded Redis 삭제 및 Exception 변경
  back/build.gradle
  back/src/main/java/com/woowacourse/teatime/auth/exception/WrongCookieTokenException.java
  back/src/main/java/com/woowacourse/teatime/auth/exception/WrongTokenException.java
  back/src/main/java/com/woowacourse/teatime/auth/service/UserAuthService.java
  back/src/test/java/com/woowacourse/teatime/auth/acceptance/AuthAcceptanceTest.java
  back/src/test/java/com/woowacourse/teatime/auth/repository/UserAuthInfoRepositoryTest.java
  back/src/test/java/com/woowacourse/teatime/auth/service/UserAuthServiceTest.java
  back/src/test/java/com/woowacourse/teatime/auth/support/EmbeddedRedisConfig.java
Labels: 🐶백엔드, 🌈리팩터링

#677 [FE] 티타임 요청 기능 구현
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/assets/request.svg
  front/src/assets/subscribe.svg
  front/src/components/Card/index.tsx
  front/src/components/Card/styles.ts
  front/src/components/Modal/styles.ts
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachProfile/styles.ts
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewMain/styles.ts
  front/src/pages/Reservation/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능, 🌈리팩터링

#678 [FE] 사전질문 관리 메뉴 분리
  front/src/App.tsx
  front/src/components/Header/index.tsx
  front/src/constants/index.ts
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachProfile/styles.ts
  front/src/pages/Question/index.tsx
  front/src/pages/Question/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#680 [BE] hotfix 브랜치 머지
  back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
Labels: 🐶백엔드, 🚀배포

#682 [FE] content type 설정
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#684 [FE] 구독하기 아이콘 제거
  front/src/components/Card/index.tsx
  front/src/components/Card/styles.ts
  front/src/pages/CrewMain/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링

#685 [BE] 콕 찔러보기 검증로직 추가
  back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
  back/src/main/java/com/woowacourse/teatime/teatime/exception/CannotPokeException.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/PokeService.java
  back/src/main/java/com/woowacourse/teatime/teatime/service/dto/poke/PokeSlackAlarmDto.java
  back/src/test/java/com/woowacourse/teatime/teatime/service/PokeServiceTest.java
Labels: 🐶백엔드, 🐞수정

#690 [BE] jar 버저닝 포맷 수정
  back/build.gradle
Labels: 🐶백엔드

#693 [BE] 무중단 배포 테스트
  back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
Labels: 🐶백엔드

#696 [FE] 누락된 이미지 사이즈 명시
  front/src/components/Card/styles.ts
Labels: 🐱프론트엔드, 🐞수정

#699 [FE] 인터셉터 설정 수정
  front/src/api/index.ts
Labels: 🐱프론트엔드, 🐞수정

#698 [FE] 스켈레톤 UI 추가
  front/src/components/Card/SkeletonCard.tsx
  front/src/components/Card/styles.ts
  front/src/constants/index.ts
  front/src/pages/CrewMain/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#701 [FE] 모바일에서 선택된 보드 상태 저장
  front/src/App.tsx
  front/src/components/BoardSelectList/index.tsx
  front/src/constants/index.ts
  front/src/context/BoardModeProvider.tsx
  front/src/mocks/data.ts
  front/src/pages/CoachMain/index.tsx
  front/src/typings/domain.ts
Labels: 🐱프론트엔드, 🌟기능

#711 [FE] 체험하기 버튼 추가
  front/src/pages/Home/index.tsx
  front/src/pages/Home/styles.ts
Labels: 🐱프론트엔드, 🌟기능

#705 [FE] 로그아웃 api 연동
  front/src/api/auth.ts
  front/src/api/index.ts
  front/src/components/Header/index.tsx
Labels: 🐱프론트엔드, 🌟기능

#713 [ALL] 무중단 배포 설정 추가
  back/src/main/java/com/woowacourse/teatime/auth/controller/AuthController.java
  back/src/main/java/com/woowacourse/teatime/auth/infrastructure/ResponseCookieTokenProvider.java
  back/src/main/resources/logback-spring.xml
Labels: 🐞수정

#714 [BE] main hotfix 수정 사항 merge
  back/src/main/resources/logback-spring.xml
Labels: 🐶백엔드, 🐞수정

#715 [BE] jar 버전 업데이트 1.6.0 -> 1.7.0
  back/build.gradle
Labels: 🐶백엔드

#718 [FE] 탭으로 시간선택시 이벤트 발생하는 에러 해결
  front/src/components/ReservationTimeList/index.tsx
  front/src/pages/Reservation/index.tsx
Labels: 🐱프론트엔드, 🐞수정

#719 [FE] 전반적인 에러처리
  front/src/App.tsx
  front/src/components/ErrorMessage/index.tsx
  front/src/components/ErrorMessage/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/components/Sheet/index.tsx
  front/src/constants/index.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/Error/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/Question/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/utils/logError.ts
Labels: 🐱프론트엔드, 🐞수정

#720 Release v1.8.1
  README.md
  front/src/App.tsx
  front/src/components/ErrorMessage/index.tsx
  front/src/components/ErrorMessage/styles.ts
  front/src/components/Header/index.tsx
  front/src/components/ReservationTimeList/index.tsx
  front/src/components/ScheduleTimeList/styles.ts
  front/src/components/Sheet/index.tsx
  front/src/constants/index.ts
  front/src/pages/Certification/index.tsx
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/pages/CrewSheet/index.tsx
  front/src/pages/Error/index.tsx
  front/src/pages/HistorySheet/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/Question/index.tsx
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
  front/src/utils/logError.ts
Labels: patch

#722 [FE] 에러 모니터링 적용
  front/package-lock.json
  front/package.json
  front/src/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/utils/logError.ts
Labels: 🐱프론트엔드, 🌟기능

#723 release 1.9.0
  front/package-lock.json
  front/package.json
  front/src/index.tsx
  front/src/pages/CrewMain/index.tsx
  front/src/utils/logError.ts
Labels: minor

#724 [FE] 스케줄 컴포넌트 함수 분리
  front/src/components/Title/index.tsx
  front/src/components/Title/styles.ts
  front/src/hooks/useSelectList.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/index.tsx
Labels: 🐱프론트엔드, 🌈리팩터링, 🐞수정

#730 [FE] 모킹 타입 수정
  front/src/mocks/browser.ts
  front/src/mocks/dummy/coachData.ts
  front/src/mocks/dummy/crewData.ts
  front/src/mocks/handlers/coachHandler.ts
  front/src/mocks/handlers/crewHandler.ts
  front/src/mocks/handlers/index.ts
Labels: 🐱프론트엔드, 🌈리팩터링

#726 [FE] 전반적인 리팩토링
  front/src/AuthRoute.tsx
  front/src/Portal.tsx
  front/src/api/coach.ts
  front/src/api/crew.ts
  front/src/api/question.ts
  front/src/components/Board/index.tsx
  front/src/components/Conditional/index.tsx
  front/src/components/DateBox/index.tsx
  front/src/components/Dropdown/index.tsx
  front/src/components/Filter/index.tsx
  front/src/components/Frame/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/ReservationInfo/index.tsx
  front/src/components/ScheduleTimeList/index.tsx
  front/src/components/Sheet/index.tsx
  front/src/components/Title/index.tsx
  front/src/context/BoardModeProvider.tsx
  front/src/context/SnackbarProvider.tsx
  front/src/context/UserProvider.tsx
  front/src/hooks/useCategory.ts
  front/src/hooks/useFetch.ts
  front/src/hooks/useRefetch.ts
  front/src/hooks/useSelectList.ts
  front/src/pages/CoachHistory/index.tsx
  front/src/pages/CoachMain/hooks/useBoard.ts
  front/src/pages/CoachMain/index.tsx
  front/src/pages/CoachProfile/index.tsx
  front/src/pages/CoachSheet/index.tsx
  front/src/pages/CrewHistory/hooks/useHistory.ts
  front/src/pages/CrewHistory/index.tsx
  front/src/pages/Reservation/hooks/useSchedule.ts
  front/src/pages/Reservation/index.tsx
  front/src/pages/Schedule/hooks/useMultipleSchedule.ts
  front/src/pages/Schedule/hooks/useSchedule.ts
  front/src/pages/Schedule/index.tsx
  front/src/pages/Schedule/utils/times.ts
  front/src/typings/domain.ts
  front/src/typings/utils.ts
  front/src/utils/date.ts
Labels: 🐱프론트엔드, 🌈리팩터링
